logging:
  level:
    root: INFO
    "[acm.internal.certification]": INFO

spring:
  profiles:
    active: dev
  application:
    name: certification
  datasource:
    url: jdbc:sqlite:certificate.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  gmail-api:
    refresh-token: "${GMAIL_REFRESH_TOKEN}"
    user-email: "${GMAIL_USER_EMAIL}"


